#Método de descomposición LU
Aunque la eliminación de Gauss representa una forma satisfactoria para resolver sistemas de ecuaciones, resulta ineficiente cuando deben resolverse ecuaciones con los mismos coeficientes $[A]$, pero con diferentes constantes de $b$.

Un motivo de introducir el método de descomposición LU es que proporciona un medio eficiente para calcular la matriz inversa, la cual tiene muchas aplicaciones.

El procecidimiento para realizar la resolución de ecuaciones por eliminación utilizando descomposición LU es el siguiente:

El primer paso es multiplicar el renglón 1 del sistema de ecuaciones por el factor (recordando eliminación de Gauss):

$f_{21}=\frac{a_{21}}{a_{11}}$

luego, este factor se le resta el segundo renglón para eliminar $a_{21}$. De forma similar, el renglón 1 se multiplica por

$f_{31}=\frac{a_{31}}{a_{11}}$

y el resultado se resta al tercer renglón para eliminar $a_{31}$. El paso final es multiplicar el segundo renglón modificado por

$f_{32}=\frac{a_{32}'}{a_{22}'}$

y restar el resultado al tercer renglón para eliminar $a_{32}'$. Entonces la matriz $[A]$ de $3\times 3$ se describe como
\begin{equation}
\begin{bmatrix}
a_{11}&a_{12}&a_{13}\\
f_{21}&a_{22}'&a_{23}'\\
f_{32}&f_{32}&a_{33}''
\end{bmatrix}
\end{equation}
esta es la descomposición LU de $[A]$ donde
\begin{equation}
[U]=
\begin{bmatrix}
a_{11}&a_{12}&a_{13}\\
0&0&a_{23}'\\
0&0&a_{33}''
\end{bmatrix}
\end{equation}
y
\begin{equation}
[L]=
\begin{bmatrix}
1&0&0\\
f_{21}&1&0\\
f_{32}&f_{32}&1
\end{bmatrix}
\end{equation}
una vez echo esto, se procede a encontrar $\{D\}$ con la relación $[L]\{D\}=\{B\}$ mediante sustitución hacia adelante. Después el resultado se sustituye en $[U]\{X\}=\{D\}$ que se resuelve con sustitución hacia atrás para encontrar $\{X\}$.

#Ejemplo
Resolver el sistema de ecuaciones:
\begin{eqnarray}
3x_1-0.1x_2-0.2x_3=7.85\\
0.1x_1+7x_2-0.3x_3=-19.3\\
0.3x_1-0.2x_2+10x_3=71.4
\nonumber
\end{eqnarray}

In [1]:
#Código hecho por:
import numpy as np
#Datos:
a = np.array([[3, -0.1, -0.2],[0.1, 7, -0.3], [0.3, -0.2, 10]])
b = np.array([7.85, -19.3, 71.4])
A = np.copy(a)
aa= np.copy(a)
m = len(a)
factor = np.zeros([m, m])
L2= np.zeros([m,m])

#Vectores que voy a encontrar:
x = np.zeros([m])
d = np.zeros([m])

In [2]:
# Funciones de descomposición de matriz a:
def descompose_U(m, a):
    for i in range (0, m-1):
        for k in range (i+1, m):
            factor [k, i] = a[k, i]/ a[i, i]
            a[k,:]= a[k,:]-a[i,:]*factor[k, i]
        #print("\nReconstruyendo queda la sig. matriz")
        #print(a)
    U = a
    return (U)

def descompose_L(m, aa, factor):
    for i in range (0, m):
        for k in range (0, m):
            if i ==k:
                L2[i,k]=1
            if i<k:
                L2[k,i]=factor [k, i]

    return (L2)

def vector_d(m, L, b, d):
    for i in range (0, m):
        if i == 0:
            d[i] = b[i]/ L[i, i]

        else:
            sumatoria=0
            for r in range(0, m):
                sumatoria = sumatoria + L[i,r]*d[r]
                #print(sumatoria)
            d[i]=(b[i]-sumatoria)/L[i,i]

    return d

def vector_x(m, U, d, x):
    for i in range (m-1, -1, -1):
        if i == (m-1):
            x[i] = d[i]/ U[i, i]

        else:
            sumatoria=0
            for r in range(0,m):
                sumatoria = sumatoria + U[i,r]*x[r]
                #print(sumatoria)
            x[i]=(d[i]-sumatoria)/U[i,i]

    return x

# El código se debe correr solo una vez

In [3]:
#Resultados:
print("La matriz inicial es:")
print(A)

U = descompose_U(m, a)
print("\nLa matriz factor es: ")
print(factor)
print("\nLa matriz U es: ")
print(U)

L = descompose_L(m, aa, factor)
print("\nLa matriz L es: ")
print(L)

d = vector_d (m, L, b, d)
print("\nEl vector d queda: ")
print(d)

x = vector_x (m, U ,d, x)
print("\nEl vector x queda: ")
print(x)

La matriz inicial es:
[[ 3.  -0.1 -0.2]
 [ 0.1  7.  -0.3]
 [ 0.3 -0.2 10. ]]

La matriz factor es: 
[[ 0.          0.          0.        ]
 [ 0.03333333  0.          0.        ]
 [ 0.1        -0.02712994  0.        ]]

La matriz U es: 
[[ 3.         -0.1        -0.2       ]
 [ 0.          7.00333333 -0.29333333]
 [ 0.          0.         10.01204188]]

La matriz L es: 
[[ 1.          0.          0.        ]
 [ 0.03333333  1.          0.        ]
 [ 0.1        -0.02712994  1.        ]]

El vector d queda: 
[  7.85       -19.56166667  70.08429319]

El vector x queda: 
[ 3.  -2.5  7. ]


#Usando librería

In [4]:
import pprint
import scipy
import scipy.linalg
import numpy as np

In [5]:
A = np.array([[3, -0.1, -0.2],[0.1, 7, -0.3], [0.3, -0.2, 10]])
B = np.array([7.85, -19.3, 71.4])
P , L, U =scipy.linalg.lu(A)

print("Matriz A")
pprint.pprint(A)
print("\nMatriz P")
pprint.pprint(P)
print("\nMatriz L")
pprint.pprint(L)
print("\nMatriz U")
pprint.pprint(U)

#Para obtener el valor de x directamente:
y = np.linalg.solve(A, B) #Así se resuelve
print("\nEl resultado de x es: ")
print(y)

Matriz A
array([[ 3. , -0.1, -0.2],
       [ 0.1,  7. , -0.3],
       [ 0.3, -0.2, 10. ]])

Matriz P
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Matriz L
array([[ 1.        ,  0.        ,  0.        ],
       [ 0.03333333,  1.        ,  0.        ],
       [ 0.1       , -0.02712994,  1.        ]])

Matriz U
array([[ 3.        , -0.1       , -0.2       ],
       [ 0.        ,  7.00333333, -0.29333333],
       [ 0.        ,  0.        , 10.01204188]])

El resultado de x es: 
[ 3.  -2.5  7. ]
