In [ ]:
#creando una clase de EDP de Laplace en dos dimensiones
#en coordenadas cartesianas
import numpy as np
class Laplace:
  def _init_(self):
    pass

  def inicio(self):
    print('Este metodo resuleve edp de laplace con n=2, m=4 y n=4, m=8')
    print('si se colocan otros valores el metodo falla')

  def intervalos(self,a,b,c,d): #los valores del intervalo
    self.a=a
    self.b=b
    self.c=c
    self.d=d

  def deltas(self,n,m): #definiendo los deltas x,y
    self.n=n
    self.m=m
    self.deltax=(self.b-self.a)/self.n
    self.deltay=(self.d-self.c)/self.m
    print('delta x=',self.deltax,'delta y=',self.deltay)

#definiendo los valores de la funcion en la frontera
  def condiciones_frontera(self,u1,u2,u3,u4):
    self.u1=u1
    self.u2=u2
    self.u3=u3
    self.u4=u4
    print('valores en la frontera: ')
    print('U1=',self.u1,'U2=',self.u2,'U3=',self.u3,'U4=',self.u4)

#Escribiendo el numero de ecuaciones en la red
  def ecuaciones_red(self):
    self.numero=(self.n-1)*(self.m-1)
    print('el numero de ecuaciones de la red es:',self.numero,'x',self.numero)

#Escribiendo la red
  def red(self):
    #import numpy as np
    if self.numero==3:
      self.u11=self.u1
      self.u12=self.u2
      self.u13=self.u2
      self.u21=self.u1
      self.u22=1 #incognita inicializada en 1---> w1
      self.u23=self.u3
      self.u31=self.u1
      self.u32=2 #incognita inicializada en 2---> w2
      self.u33=self.u3
      self.u41=self.u1
      self.u42=3 #incognita inicializada en 3---> w3
      self.u43=self.u3
      self.u51=self.u4
      self.u52=self.u4
      self.u53=self.u4
      self.U=[[self.u11,self.u12,self.u13],
              [self.u21,self.u22,self.u23],
              [self.u31,self.u32,self.u33],
              [self.u41,self.u42,self.u43],
              [self.u51,self.u52,self.u53]]
      self.red=np.matrix(self.U)
      print(len(self.U))
      print('la red es: ')
      print(self.red)
      print('los numeros 1,2 y 3 son incognitas')
    elif self.numero==21:
      self.w11=self.u1
      self.w12=self.u2
      self.w13=self.u2
      self.w14=self.u2
      self.w15=self.u2
      self.w21=self.u1
      self.w22=1
      self.w23=8
      self.w24=15
      self.w25=self.u3
      self.w31=self.u1
      self.w32=2
      self.w33=9
      self.w34=16
      self.w35=self.u3
      self.w41=self.u1
      self.w42=3
      self.w43=10
      self.w44=17
      self.w45=self.u3
      self.w51=self.u1
      self.w52=4
      self.w53=11
      self.w54=18
      self.w55=self.u3
      self.w61=self.u1
      self.w62=5
      self.w63=12
      self.w64=19
      self.w65=self.u3
      self.w71=self.u1
      self.w72=6
      self.w73=13
      self.w74=20
      self.w75=self.u3
      self.w81=self.u1
      self.w82=7
      self.w83=14
      self.w84=21
      self.w85=self.u3
      self.w91=self.u4
      self.w92=self.u4
      self.w93=self.u4
      self.w94=self.u4
      self.w95=self.u4
      self.U1=[[self.w11,self.w12,self.w13,self.w14,self.w15],
               [self.w21,self.w22,self.w23,self.w24,self.w25],
               [self.w31,self.w32,self.w33,self.w34,self.w35],
               [self.w41,self.w42,self.w43,self.w44,self.w45],
               [self.w51,self.w52,self.w53,self.w54,self.w55],
               [self.w61,self.w62,self.w63,self.w64,self.w65],
               [self.w71,self.w72,self.w73,self.w74,self.w75],
               [self.w81,self.w82,self.w83,self.w84,self.w85],
               [self.w91,self.w92,self.w93,self.w94,self.w95]]
      self.red1=np.matrix(self.U1)
      print('la red es: ')
      print(self.red1)
      print('los numeros 1 al 21 son incognitas')
    else :
      print('lo siento no puedo escribir la red')

#Planteando las ecuaciones
  def ecuaciones(self):
    self.A=[[0,0,0],
            [0,0,0],
            [0,0,0]]
    self.A1=[[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
             [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
             [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
             [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
             [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
             [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
             [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
             [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
             [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
             [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
             [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
             [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
             [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
             [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
             [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
             [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
             [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
             [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
             [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
             [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
             [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]]
    if self.deltax==self.deltay:
     if self.numero==3:
       self.j=2
       self.i=2
       self.contador=1
       while self.i<=4:
         self.ec1=[-2*self.U[self.i-1][self.j-1],
                   -2*self.U[self.i-1][self.j-1],
                   self.U[self.i-2][self.j-1],
                   self.U[self.i][self.j-1],
                   self.U[self.i-1][self.j-2],
                   self.U[self.i-1][self.j]]
         self.k=int((self.ec1[0]+self.ec1[1])/(-4))-1
         self.A[self.k][self.k]=-4 #asigna el -4 a la matriz en la diagonal
         self.l=2
         while self.l<=5:
          if self.ec1[self.l]==1:
            self.A[self.k][0]=1
          elif self.ec1[self.l]==2:
            self.A[self.k][1]=1
          elif self.ec1[self.l]==3:
            self.A[self.k][2]=1
          self.l+=1
         #print('elementos de la ecuacion ',self.contador,':')
         #print(self.ec1)
         self.i+=1
         self.contador+=1
       #print('A=')
       #print(np.matrix(self.A))
     elif self.numero==21:
      self.j=2
      self.contador=1
      while self.j<=4:
       self.i=2
       while self.i<=8:
        self.ec2=[-2*self.U1[self.i-1][self.j-1],
                  -2*self.U1[self.i-1][self.j-1],
                  self.U1[self.i-2][self.j-1],
                  self.U1[self.i][self.j-1],
                  self.U1[self.i-1][self.j-2],
                  self.U1[self.i-1][self.j]]
        self.k=int((self.ec2[0]+self.ec2[1])/(-4))-1
        self.A1[self.k][self.k]=-4
        self.l=2
        while self.l<=5:
          self.l1=1
          while self.l1<=21:
           if self.ec2[self.l]==self.l1:
            self.A1[self.k][self.l1-1]=1
           self.l1+=1
          self.l+=1
        #print('elementos de la ecuacion ',self.contador,':')
        #print(self.ec2)
        self.i+=1
        self.contador+=1
       self.j+=1
      #print('A1=')
      #print(np.matrix(self.A1))
     else :
        print('lo siento, solo puedo hacer sistemas 3x3 y 21x21')
    else:
      print('los siento, solo puedo plantear ecuaciones para deltas iguales')

  def resuelve(self):
    if self.numero==3:
      self.A11=np.matrix(self.A)
      self.b1=np.matrix([[0],[0],[-100]])
      self.w=(self.A11**-1)*self.b1
      print('la solucion del sistema es:')
      print('x=')
      print(self.w)
    elif self.numero==21:
      self.A12=np.matrix(self.A1)
      self.b2=np.matrix([[0],[0],[0],[0],[0],[0],[-100],
                         [0],[0],[0],[0],[0],[0],[-100],
                         [0],[0],[0],[0],[0],[0],[-100]])
      self.w1=(self.A12**-1)*self.b2
      print('la solucion del sistema es:')
      print('x=')
      print(self.w1)

Edp=Laplace()
Edp.inicio()
Edp.intervalos(0,10,0,20) #a,b,c,d
Edp.deltas(4,8) #n,m
Edp.condiciones_frontera(0,0,0,100)
Edp.ecuaciones_red()
Edp.red()
Edp.ecuaciones()
Edp.resuelve()

Este metodo resuleve edp de laplace con n=2, m=4 y n=4, m=8
si se colocan otros valores el metodo falla
delta x= 2.5 delta y= 2.5
valores en la frontera: 
U1= 0 U2= 0 U3= 0 U4= 100
el numero de ecuaciones de la red es: 21 x 21
la red es: 
[[  0   0   0   0   0]
 [  0   1   8  15   0]
 [  0   2   9  16   0]
 [  0   3  10  17   0]
 [  0   4  11  18   0]
 [  0   5  12  19   0]
 [  0   6  13  20   0]
 [  0   7  14  21   0]
 [100 100 100 100 100]]
los numeros 1 al 21 son incognitas
la solucion del sistema es:
x=
[[ 0.35300681]
 [ 0.91317668]
 [ 2.01031126]
 [ 4.29571775]
 [ 9.1531684 ]
 [19.66317668]
 [43.21014967]
 [ 0.49885056]
 [ 1.28938863]
 [ 2.83235062]
 [ 6.01939133]
 [12.65377919]
 [26.28938863]
 [53.17742199]
 [ 0.35300681]
 [ 0.91317668]
 [ 2.01031126]
 [ 4.29571775]
 [ 9.1531684 ]
 [19.66317668]
 [43.21014967]]
