#Eliminación Gauss-Jordan
El método de Gauss-Jordan es una variante del método de eliminación de Gauss. La principal diferencia es que cuando una incógnita se elimina en el método de Gauss_Jordan, ésta se elimina de todas las ecuaciones. De esta forma, el paso de eliminación genera una matriz identidad y no una triangular. En consecuencia, no es necesario usar la sustitución hacia atrás. Esto se explica mejor con un ejemplo.

#Ejemplo:
Resolver el siguiente sistema de ecuaciones con el método de Gauss-Jordan
\begin{eqnarray}
2x_1+3x_2+x_3+2x_4=1\\2x_1+4x_2-x_3+5x_4=2\\3x_1+7x_2+1.5x_3+x_4=3\\6x_1-9x_2+3x_3+7x_4=4
\end{eqnarray}

In [1]:
#Código hecho por: Diana Ailed Hernández Bustos
import numpy as np
#se escribe la matriz
a = np.array([[2,3,1,2, 1],[2,4,-1,5,2],[3,7,1.5,1, 3],[6,-9,3,7, 4]])
aa= np.copy(a)
m = len(a)
n = m+1
#print(aa)
#print(m)

In [2]:
#Primero, se hace la eliminación de ceros por debajo
for i in range (0, m):
    for k in range (i+1, m):
        z = a[i,i]
        #print(z)
        a[i, :] =  a[i, :]/ z #Correcto

        factor = a[k, i]/ a[i, i]
        a[k,:]= a[k,:]-a[i,:]*factor

    if i != m-1:
        print("\nReconstruyendo la matriz", i+1)
        print(a)

b = np.copy(a)

print("\nAhora, elimino los ceros por arriba:")
#Después, se hace la eliminación de ceros por arriba
l = m-1
for i in range (l, -1, -1):
    for k in range (i-1, -1, -1):
        z = b[i,i]
        #print(z)
        b[i, :] =  b[i, :]/ z #Correcto

        factor = b[k, i]/ b[i, i]
        b[k,:]= b[k,:]-b[i,:]*factor

    if i != 0:
        print("\nReconstruyendo la matriz")
        print(b)

#Resultados:
print("\nLos resultados son:\n")
for i in range (0, m):
    x = b[i, m]
    print("x{} = {}".format(i+1, x))


Reconstruyendo la matriz 1
[[  1.    1.5   0.5   1.    0.5]
 [  0.    1.   -2.    3.    1. ]
 [  0.    2.5   0.   -2.    1.5]
 [  0.  -18.    0.    1.    1. ]]

Reconstruyendo la matriz 2
[[  1.    1.5   0.5   1.    0.5]
 [  0.    1.   -2.    3.    1. ]
 [  0.    0.    5.   -9.5  -1. ]
 [  0.    0.  -36.   55.   19. ]]

Reconstruyendo la matriz 3
[[  1.    1.5   0.5   1.    0.5]
 [  0.    1.   -2.    3.    1. ]
 [  0.    0.    1.   -1.9  -0.2]
 [  0.    0.    0.  -13.4  11.8]]

Ahora, elimino los ceros por arriba:

Reconstruyendo la matriz
[[ 1.          1.5         0.5         0.          1.38059701]
 [ 0.          1.         -2.          0.          3.64179104]
 [ 0.          0.          1.          0.         -1.87313433]
 [-0.         -0.         -0.          1.         -0.88059701]]

Reconstruyendo la matriz
[[ 1.          1.5         0.          0.          2.31716418]
 [ 0.          1.          0.          0.         -0.10447761]
 [ 0.          0.          1.          0.       